# Generated by hexgate policy build — do not edit by hand.
# Compiled from policy.yaml (sha256: GOLDEN_FIXED_HASH).
# Regenerate with: hexgate policy build <source>

package hexgate.policy

import rego.v1

default allow := false
default requires_approval := false

# Single entrypoint — runtime queries data.hexgate.policy.decision.
decision := {
    "allow": allow,
    "requires_approval": requires_approval,
    "violations": violations,
}

# ---- role: billing -----------------------------------------------------
allow if {
    input.role == "billing"
    input.tool == "fetch"
}

requires_approval if {
    input.role == "billing"
    input.tool == "issue_credit"
    input.args.amount <= 500
}

violations contains `args.amount <= 500` if {
    input.role == "billing"
    input.tool == "issue_credit"
    not input.args.amount <= 500
}

allow if {
    input.role == "billing"
    input.tool == "read_file"
}

allow if {
    input.role == "billing"
    input.tool == "refund_order"
    input.args.amount <= 500
    input.args.currency == "USD"
    input.args.template in ["a", "b"]
    not input.args.priority in ["urgent"]
    input.args.confirmed == true
    input.args.payment.amount <= 100
}

violations contains `args.amount <= 500` if {
    input.role == "billing"
    input.tool == "refund_order"
    not input.args.amount <= 500
}

violations contains `args.currency == "USD"` if {
    input.role == "billing"
    input.tool == "refund_order"
    not input.args.currency == "USD"
}

violations contains `args.template in ["a", "b"]` if {
    input.role == "billing"
    input.tool == "refund_order"
    not input.args.template in ["a", "b"]
}

violations contains `args.priority not in ["urgent"]` if {
    input.role == "billing"
    input.tool == "refund_order"
    input.args.priority in ["urgent"]
}

violations contains `args.confirmed == true` if {
    input.role == "billing"
    input.tool == "refund_order"
    not input.args.confirmed == true
}

violations contains `args.payment.amount <= 100` if {
    input.role == "billing"
    input.tool == "refund_order"
    not input.args.payment.amount <= 100
}

# ---- role: default -----------------------------------------------------
allow if {
    not input.role in {"billing", "support"}
    input.tool == "web_search"
}

# ---- role: support -----------------------------------------------------
allow if {
    input.role == "support"
    input.tool == "fetch"
}

requires_approval if {
    input.role == "support"
    input.tool == "issue_credit"
    input.args.amount <= 500
}

violations contains `args.amount <= 500` if {
    input.role == "support"
    input.tool == "issue_credit"
    not input.args.amount <= 500
}

allow if {
    input.role == "support"
    input.tool == "read_file"
}

# Sentinel: keeps `violations` defined even when no constraint rules exist.
violations contains "__never__" if false

