"""Compile a Hexgate ``policy.yaml`` document into a Rego policy module.

The compiler is a pure-Python transformation: parsed YAML payload →
``PolicySet`` (which flattens ``inherits:`` and drops ``is_mixin:`` entries)
→ a Rego source string suitable for ``opa build -t wasm``.

Why this lives in the SDK (not just the platform): the same compiler runs
in three places — the platform's save-time pipeline, the ``hexgate policy
build`` CLI a dev uses for local iteration, and CI/CD wrapper scripts.
Identical artifacts everywhere; the only thing the platform adds is the
Ed25519 signature on the resulting bundle.

Output structure
----------------

The module exposes a single ``decision`` entrypoint that returns the
full verdict as a structured object. The runtime evaluates one query
per tool-call and receives back ``{allow, requires_approval, violations}``:

    package hexgate.policy

    import rego.v1

    default allow := false
    default requires_approval := false

    # The single entrypoint the runtime queries.
    decision := {
        "allow": allow,
        "requires_approval": requires_approval,
        "violations": violations,
    }

    # ---- role: billing ----
    allow if {
        input.role == "billing"
        input.tool == "refund_order"
        input.args.amount <= 500
    }

    violations contains `args.amount <= 500` if {
        input.role == "billing"
        input.tool == "refund_order"
        not input.args.amount <= 500
    }

Deny is implicit — a tool with ``mode: deny`` produces no allow rule and
no violation rules, so ``allow`` stays false and the deny reason is
just "no allow rule matched" (caller's job to surface that).

The ``violations`` set carries the raw constraint string from the YAML
verbatim, so deny reasons in production match exactly what the dev
wrote in their policy file.

Constraint translation
----------------------

The grammar already mirrors Rego conditions, so translation is one step:
each ``args.<field>`` path becomes ``input.args.<field>``. We re-use
:func:`parse_constraint` for the AST so the path / operator / literal are
already structured — we don't text-substitute. Every constraint emits
*two* contributions: one positive (added to the allow rule body) and
one negative (a ``violations contains`` rule).
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from hexgate.security.constraints import Cmp, Lit, Node, Operand, Ref, parse_constraint
from hexgate.security.models import AgentPolicy, BaseToolPolicy, FileToolPolicy
from hexgate.security.policy_set import (
    DEFAULT_ROLE_NAME,
    PolicySet,
    PolicySetError,
    load_policy_set_from_dict,
)


# Rego operators are mostly a superset of ours. ``not in`` needs special
# handling because Rego writes it as ``not (x in y)``; we wrap the body.
_INFIX_OPS = {"==", "!=", "<", "<=", ">", ">="}


def compile_to_rego(
    payload: dict[str, Any],
    *,
    package: str = "hexgate.policy",
    source_hash: str | None = None,
) -> str:
    """Render a Rego policy module for ``payload``.

    ``payload`` is the parsed YAML document (the same shape
    :func:`load_policy_set_from_dict` accepts — flat single-policy or
    inline-roles). ``source_hash`` is the sha256 of the original YAML
    source; included in the file header so the artifact is traceable
    back to its source. When ``None``, the header is computed from
    ``payload`` itself.
    """
    policy_set = load_policy_set_from_dict(payload)
    if source_hash is None:
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        source_hash = hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    lines: list[str] = []
    lines.extend(_header(source_hash, package))
    lines.extend(_decision_scaffold())
    lines.extend(_role_rules(policy_set))
    lines.extend(_violations_sentinel())
    # Trailing newline — POSIX-friendly + a few editors complain otherwise.
    return "\n".join(lines) + "\n"


def _header(source_hash: str, package: str) -> list[str]:
    return [
        "# Generated by hexgate policy build — do not edit by hand.",
        f"# Compiled from policy.yaml (sha256: {source_hash}).",
        "# Regenerate with: hexgate policy build <source>",
        "",
        f"package {package}",
        "",
        "import rego.v1",
        "",
    ]


def _decision_scaffold() -> list[str]:
    """The top-level decision object + default boolean rules.

    Every rendered module has exactly this scaffold; the per-role rules
    contribute to ``allow``, ``requires_approval``, and ``violations``
    via the rules emitted below.
    """
    return [
        "default allow := false",
        "default requires_approval := false",
        "",
        "# Single entrypoint — runtime queries data.hexgate.policy.decision.",
        "decision := {",
        '    "allow": allow,',
        '    "requires_approval": requires_approval,',
        '    "violations": violations,',
        "}",
        "",
    ]


def _violations_sentinel() -> list[str]:
    """Keep ``violations`` defined even for constraint-free policies.

    Without at least one ``violations contains`` rule in the module,
    opa flags the symbol as unsafe and refuses to build. The sentinel
    body is ``false`` so it never contributes — the set stays empty
    in the happy path.
    """
    return [
        "# Sentinel: keeps `violations` defined even when no constraint rules exist.",
        'violations contains "__never__" if false',
        "",
    ]


def _role_rules(policy_set: PolicySet) -> list[str]:
    """Emit per-role allow / requires_approval / violations rules.

    Roles ordered alphabetically and tools within a role ordered the same
    way so the output is deterministic regardless of dict insertion order
    (Python 3.7+ preserves it, but YAML loaders may differ in edge cases).
    """
    out: list[str] = []
    role_names = sorted(role for role in policy_set.roles)
    non_default = [r for r in role_names if r != DEFAULT_ROLE_NAME]
    for role in role_names:
        policy = policy_set.policy_for(role)
        role_guard = _role_guard(role, non_default)
        rules = list(_rules_for_role(role, policy, role_guard))
        if not rules:
            # Pure deny — skip the section entirely to keep the output tight.
            continue
        out.append(f"# ---- role: {role} {'-' * (60 - len(role))}")
        out.extend(rules)
    return out


def _role_guard(role: str, non_default: list[str]) -> list[str]:
    """Body line(s) selecting which caller role a rule applies to.

    A named role matches exactly (``input.role == "billing"``). The
    ``default`` role is the *fallback*: it must fire for ``role == "default"``,
    a null/absent role, AND any role not otherwise defined — mirroring
    :meth:`PolicySet.policy_for`'s unknown-role fallback. A single exclusion
    of the other concrete roles covers all three cases at once (and an
    all-deny role, which emits no rules, still stays excluded because it's in
    the concrete-role set passed here).
    """
    if role != DEFAULT_ROLE_NAME:
        return [f'    input.role == "{_escape_string(role)}"']
    if not non_default:
        return []  # default is the only role → it applies to every caller
    members = ", ".join(json.dumps(name) for name in non_default)
    return [f"    not input.role in {{{members}}}"]


def _rules_for_role(role: str, policy: AgentPolicy, role_guard: list[str]) -> list[str]:
    """Render rules for one resolved role (allow + violations per tool).

    Explicitly-listed tools each get their own ``input.tool == "X"`` rule;
    ``default_policy`` (when not ``deny``) gets a catch-all for any tool *not*
    explicitly listed — mirroring the pydantic engine's
    ``policy.tools.get(tool, default_policy)`` fallback so both engines agree
    on unlisted tools.
    """
    listed = sorted(policy.tools)
    out: list[str] = []
    for tool_name in listed:
        tool_guard = [f'    input.tool == "{_escape_string(tool_name)}"']
        out.extend(
            _gated_rules(
                role, role_guard, tool_guard, policy.tools[tool_name], tool_name
            )
        )
    out.extend(_default_rules(role, role_guard, policy.default_policy, listed))
    return out


def _default_rules(
    role: str,
    role_guard: list[str],
    default_policy: BaseToolPolicy,
    listed: list[str],
) -> list[str]:
    """Catch-all rules for ``default_policy`` — any tool not explicitly listed.

    ``deny`` (the default) emits nothing: absence of a rule IS the deny. For
    ``allow`` / ``approval_required`` the tool guard excludes the listed tools
    so they keep using their own policy.
    """
    if default_policy.mode == "deny":
        return []
    if listed:
        members = ", ".join(json.dumps(name) for name in listed)
        tool_guard = [f"    not input.tool in {{{members}}}"]
    else:
        tool_guard = []  # nothing listed → the default applies to every tool
    return _gated_rules(role, role_guard, tool_guard, default_policy, "<default>")


def _gated_rules(
    role: str,
    role_guard: list[str],
    tool_guard: list[str],
    tool_policy: BaseToolPolicy,
    label: str,
) -> list[str]:
    """Render the positive + per-constraint violation rules for one policy.

    ``role_guard`` / ``tool_guard`` are the body line(s) selecting which
    caller(s) and tool(s) the rule applies to. ``label`` names the tool (or
    ``<default>``) for constraint parse errors.

    ``deny`` mode emits nothing — absence of a rule IS the deny.
    """
    if tool_policy.mode == "deny":
        return []
    # file_scope is a pydantic-engine-only feature — the Rego compiler has no
    # path-glob translation yet, so silently dropping it would compile to a
    # FAIL-OPEN bundle (the path restriction lost, every path allowed). Refuse
    # to build rather than ship a bundle weaker than the source policy. Only
    # matters for non-deny modes (deny never consults file_scope on either
    # engine), so this is reached after the deny short-circuit above.
    if isinstance(tool_policy, FileToolPolicy) and tool_policy.file_scope is not None:
        raise PolicySetError(
            f"role {role!r} tool {label!r}: file_scope is not supported by the "
            "WASM/Rego engine yet — compiling would produce a fail-open bundle "
            "(the path restriction silently dropped). Enforce this policy on the "
            "pydantic engine, or remove file_scope before building a bundle."
        )
    head = "allow" if tool_policy.mode == "allow" else "requires_approval"

    # Parse all constraints up-front — surfaces bad grammar at compile time.
    parsed: list[tuple[str, Node]] = []
    for raw_constraint in tool_policy.constraints:
        try:
            parsed.append((raw_constraint, parse_constraint(raw_constraint)))
        except Exception as exc:
            raise PolicySetError(
                f"role {role!r} tool {label!r}: invalid constraint "
                f"{raw_constraint!r}: {exc}"
            ) from exc

    guard = [*role_guard, *tool_guard]
    out: list[str] = []
    out.extend(_positive_rule(guard, head, parsed))
    out.append("")
    for raw, node in parsed:
        out.extend(_violation_rule(guard, raw, node))
        out.append("")
    return out


def _positive_rule(
    guard: list[str],
    head: str,
    parsed: list[tuple[str, Node]],
) -> list[str]:
    """``allow if { <guard>; constraint1; constraint2; ... }``."""
    body = list(guard)
    for _, node in parsed:
        body.append(f"    {_node_to_rego(node)}")
    if not body:
        # Unconditional rule (only-default role, default_policy allow, no
        # tools/constraints) — an empty ``{}`` body is invalid Rego.
        body = ["    true"]
    return [f"{head} if {{", *body, "}"]


def _violation_rule(
    guard: list[str],
    raw_constraint: str,
    node: Node,
) -> list[str]:
    """``violations contains <raw> if { <guard>; not constraint }``.

    The membership value is the original constraint string from the YAML
    so deny reasons match exactly what the dev wrote.
    """
    return [
        f"violations contains {_rego_string(raw_constraint)} if {{",
        *guard,
        f"    {_negated_node_to_rego(node)}",
        "}",
    ]


def _negated_node_to_rego(node: Node) -> str:
    """Render the logical negation of a node — the violation-rule condition.

    For most comparisons this is ``not <cond>``. For ``not in`` the base
    rendering is *already* ``not X in Y``; its negation is the plain
    ``X in Y`` — emitting ``not not X in Y`` is a Rego parse error, so any
    policy with a ``not in`` constraint would otherwise fail to compile.
    """
    if isinstance(node, Cmp) and node.op == "not in":
        return f"{_render(node.left)} in {_render(node.right)}"
    return f"not {_node_to_rego(node)}"


def _node_to_rego(node: Node) -> str:
    """Render one node as a Rego condition line. One node kind today (``Cmp``)."""
    if isinstance(node, Cmp):
        return _cmp_to_rego(node)
    # Unreachable given parse_constraint's whitelist, but defensive.
    raise PolicySetError(f"cannot render node {node!r}")


def _cmp_to_rego(node: Cmp) -> str:
    """Render a comparison as a Rego condition line.

    Path translation: ``args.amount`` → ``input.args.amount``. We always
    prefix ``input.`` so the rule body reads from the WASM evaluator's
    input dict (the conventional name in OPA's eval model).
    """
    lhs = _render(node.left)
    rhs = _render(node.right)
    op = node.op
    if op in _INFIX_OPS:
        return f"{lhs} {op} {rhs}"
    if op == "in":
        return f"{lhs} in {rhs}"
    if op == "not in":
        # Rego negates the whole ``in`` expression; semantically identical
        # to "not present in the set."
        return f"not {lhs} in {rhs}"
    # Unreachable given parse_constraint's whitelist, but defensive.
    raise PolicySetError(f"unsupported constraint operator {op!r}")


def _render(operand: Operand) -> str:
    """Render an operand as Rego source.

    A ``Ref`` becomes an ``input.``-prefixed accessor; a ``Lit`` becomes a
    JSON literal (strings double-quoted with escapes, numbers bare, booleans
    ``true``/``false``, lists bracketed — Rego's literal grammar is a superset
    of JSON for these shapes).
    """
    if isinstance(operand, Ref):
        return "input." + ".".join(operand.path)
    if isinstance(operand, Lit):
        return json.dumps(operand.value)
    raise PolicySetError(f"cannot render operand {operand!r}")


def _escape_string(value: str) -> str:
    """Escape a Python string for safe embedding inside Rego ``"..."``.

    Same rules as JSON: backslashes and double-quotes need escaping. We
    use json.dumps + slice to share the implementation.
    """
    return json.dumps(value)[1:-1]


def _rego_string(value: str) -> str:
    """Render a string as a Rego literal — backticks when safe, else JSON.

    Backticks are Rego's raw-string syntax: no escape processing inside.
    That's perfect for constraint strings like ``args.currency in ["USD"]``
    where double-quote escaping would be noisy. The fallback to JSON
    handles the rare case where the constraint itself contains a backtick.
    """
    if "`" not in value:
        return f"`{value}`"
    return json.dumps(value)


def compile_default_only(
    policy: AgentPolicy, *, package: str = "hexgate.policy"
) -> str:
    """Compile a flat single-policy ``AgentPolicy`` as a one-role module.

    Convenience for callers that already have an ``AgentPolicy`` model in
    hand (e.g. legacy single-policy agents). Wraps it as the ``default``
    role and delegates to :func:`compile_to_rego`.
    """
    payload = {
        "version": policy.version,
        "roles": {DEFAULT_ROLE_NAME: policy.model_dump(exclude_defaults=False)},
    }
    return compile_to_rego(payload, package=package)
